#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x lemonbuddy >/dev/null; do sleep 1; done

if [[ "$1" == "kill" ]]; then
    exit
fi

if xrandr | grep "HDMI1 connected" > /dev/null; then
    polybar left_bar &
    polybar right_bar &
else
    polybar laptop_bar &
fi
