#!/usr/bin/env bash

if ! pgrep mpv; then
  exec mpv --input-ipc-server=/tmp/mpvsock --keepaspect-window "$1" "$2" &
fi

echo ' { "command": ["loadfile", "'"$1"'", "append-play"] }' | socat - /tmp/mpvsock
