#!/bin/sh

bspc config external_rules_command "$(dirname $0)/external_rules"

bspc monitor LVDS1 -d home term web
bspc monitor HDMI1 -d code media etc

bspc config -m ^1 border_width  2
bspc config -m ^2 border_width  2

bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer   true
bspc config pointer_follows _focus  true

bspc config normal_border_color "#1D1F21"
bspc config active_border_color "#1D1F21"
bspc config focused_border_color "#3266A0"
bspc config presel_feedback_color "#9a875f"
bspc config urgent_border_color "#9f7155"
bspc config focused_locked_border_color "#9a875f"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a URxvt:floating state=floating
bspc rule -a URxvt:mpd_cava state=floating sticky=on
bspc rule -a Conky desktop=home state=floating sticky=off border=off layer=below private=on


feh --bg-fill ~/.wallpapers/wall.png
toggle-touchpad
bars
compton &
