#!/usr/bin/env bash

activeWorkspace() {
    while read -r line ; do
        case $line in
            W*)
                activeWS=""
                isFocused=0
                IFS=':'
                set -- ${line#?}
                while [ $# -gt 0 ] ; do
                    item=$1
    				name=${item#?}
                    case $item in
                        M*)
                            isFocused=1
                            ;;
                        m*)
                            isFocused=0
                            ;;
                        [FO]* )
                            if [[ $isFocused -eq 1 ]]; then
                                activeWS="${name}"
                            fi
                            ;;
                    esac
                    shift
                done
                ;;
        esac
        #formatted=$(python -c "print('{:^10}'.format('${activeWS}'))")
        echo "%{B#292b2e}%{F#afafaf}  ${activeWS}  %{F-}%{B-}"
    done
}

bspc subscribe report | activeWorkspace
