#!/usr/bin/env bash

while true; do
    echo -e "%{F$1}\ue0aa%{F-} 0"
    available_packages=$(checkupdates | wc -l)
    echo -e "%{F$1}\ue0aa%{F-} $available_packages"
    sleep 1800 # sleep 30mins
done
